# Generated by Django 3.2.6 on 2021-08-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210827_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
