# Generated by Django 3.2.6 on 2021-08-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210827_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
