# Generated by Django 3.2.6 on 2021-08-27 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start', models.DateField(default=datetime.datetime.today)),
                ('end', models.DateField()),
                ('create_at', models.DateField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Products',
                'ordering': ('-name',),
                'managed': True,
            },
        ),
    ]
