# Generated by Django 3.2.6 on 2021-08-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='end',
        ),
        migrations.RemoveField(
            model_name='products',
            name='start',
        ),
    ]
